pipeline {
    agent {
        docker {
            image 'ruby'
        } 
    }

    stages {
        stage('Preparation') {
            steps {
                sh 'bundle install'
            }
        }
        stage('Testing API') {
            steps {
                sh  'rspec'
            }
        }
    }
}