pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network rocklov-network'
        } 
    }

    stages {
        stage('Preparation') {
            steps {
                sh 'cd api && bundle install'
            }
        }
        stage('Testing API') {
            steps {
                sh  'cd api && rspec'
            }
        }
    }
}