source "https://rubygems.org"

gem "allure-cucumber", "2.13.9"
gem "capybara", "3.33"
gem "cucumber", "5.2"
gem "faker", "2.14"
gem "mongo", "2.13.1"
gem "rufo"
gem "rspec", "3.10"
gem "selenium-webdriver", "3.142.7"
gem 'httparty', '0.18.1'
